version: "3.8"

services:
  nodeapp:
    build:
      context: .
      dockerfile: Dockerfile.custom
    container_name: nodeapp
    expose:
      - "3000"
    restart: always

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    depends_on:
      - nodeapp
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    restart: always
